import random
class compPlayer():
    def __init__(self, name, maxPoints):
        self.points = 0
        self.name = name
        self.maxPoints = maxPoints

    #we will make this randomly generated by questions later instead of total points so it would be like the bot is playing
    def totalPoints(self):
        self.points = random.randint(0,self.maxPoints)
        return self.points

def makeList(file): #adds words individually into a list
    questions = []
    questions = file.split()

    return (questions)

def main():
    file = open("Questions.csv", "r") #reading file
    quiz = file.read()
    qList = []
    qList = makeList(quiz)
    print(qList)
    numQuestions = int(input("How many questions do you want (1-30)?"))
    print("Okay you will have " + str(numQuestions) + " questions")

    numBots = int(input("How man players do you want to play against (0-3)?"))
    print("Okay you will be playing against " + str(numBots) + " computer(s)")
    for bots in range (numBots):
        maxPoints = numQuestions
        bot = compPlayer("Computer" + str(bots+1), maxPoints)
        print(bot.name)
        print(bot.totalPoints())

    playerPoints = 0
    q = 6
    for q in range (numQuestions):
        print("Question:")
        print(qList[q])
        print("")
        print("Answer Choices:")
        q += 1
        print(qList[q])
        q += 1
        print(qList[q])
        q += 1
        print(qList[q])
        q += 1
        print(qList[q])
        q += 1
        print("")
        x = input()

        if x == qList[q]:
            playerPoints += 1
            print("Good Job, you have " + str(playerPoints) + " points")
        else:
            print("You Suck, you have " +str(playerPoints) +" points")



main()